### ISSUE TITLE
MW3 bug

### ISSUE THREAD

**Issue by max100n1** [sheilan102/husky_modified#1]
Load a supported CoD Game, then click the paper plane to export loaded BSP data.

Found supported game: Call of Duty: Modern Warfare 3
Loaded Gfx Map     -   maps/mp/mp_hardhat.d3dbsp
Loaded Map         -   mp_hardhat
Vertex Count       -   359911
Indices Count      -   713205
Surface Count      -   11265
Model Count        -   3574
Parsing vertex data....
Parsed vertex data in 1,23 seconds.
Parsing surface indices....
Parsed indices in 0,01 seconds.
Parsing surfaces....
Parsed surfaces in 0,08 seconds.
Converting to OBJ....
An unhandled exception has occured:
System.ArgumentException: Путь содержит недопустимые знаки.
   в System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   в System.IO.Path.GetFileName(String path)
   в System.IO.Path.GetFileNameWithoutExtension(String path)
   в Husky.ModernWarfare3.ExportBSPData(ProcessReader reader, Int64 assetPoolsAddress, Int64 assetSizesAddress, String gameType, Action`1 printCallback) в F:\cod4 WORK\Softwares\Husky-master\Husky-master\src\Husky\Husky\Games\ModernWarfare3.cs:строка 326
   в Husky.HuskyUtil.LoadGame(Action`1 printCallback) в F:\cod4 WORK\Softwares\Husky-master\Husky-master\src\Husky\Husky\HuskyUtil.cs:строка 96

**Comment by sheilan102** [comment]
I'll look into it.

Edit: Should would with latest release.

**Comment by max100n1** [comment]
Everything works fine on the latest release!
thank you very much!

**Comment by TurdSnack** [comment]
Im having this similar issue on MW2 where the tool is referencing some file on the F: drive
![C2MIssue](https://user-images.githubusercontent.com/45889703/57172986-b5b0b400-6ddc-11e9-9759-7e1f6877329f.PNG)

**Comment by sheilan102** [comment]
I'll look into it.

**Comment by sheilan102** [comment]
> Im having this similar issue on MW2 where the tool is referencing some file on the F: drive
> ![C2MIssue](https://user-images.githubusercontent.com/45889703/57172986-b5b0b400-6ddc-11e9-9759-7e1f6877329f.PNG)

Fixed & added map entities support for MW2.
MW3 support to come later.
