### ISSUE TITLE
Black Ops 1 not detected

### ISSUE THREAD

**Issue by valenrss** [sheilan102/husky_modified#12]
For versions greater than beta 2.0
Black Ops 1 is not detected (sp)

**Comment by FailordzZ** [comment]
True, works with older version
Thanks you for the answer ;)

**Comment by Rickgrendel** [comment]
Any news on this? I would really like to use the new C2M features with BO1

**Comment by Rickgrendel** [comment]
Okay, I found a solution. if you build the project yourself the program works as expected.

**Comment by FanSeaJay** [comment]
> s expected.

How do you go about doing this?

**Comment by Deaz750xx** [comment]
> Okay, I found a solution. if you build the project yourself the program works as expected.

How you doing this ?

**Comment by sheilan102** [comment]
Works with latest version.
