### ISSUE TITLE
Modern Warfare Remaster 2

### ISSUE THREAD

**Issue by DeviousLobster** [sheilan102/husky_modified#14]
Hello there, Love your work it is Amazing 

Is there a plan or a possibility of getting C2M to support Modern Warfare 2 Remaster ?
It would be a great addition. 

The MWR2 should be using the Modified Upgraded Version of Sledgehammer Game Engine since it uses the same structure for creating levels just like every other Cod Game that came before. 

I think it should be easier to do than Modern Warfare 2019 since that games uses a New Game Engine completely built from the ground up.

If the task is to difficult to do don't bother or strain yourself over it

I hope you succeed, including any of your future Projects

**Comment by sheilan102** [comment]
No plans to support MW2CR.
