### ISSUE TITLE
BLACK OPS 1 NOT DETECTED

### ISSUE THREAD

**Issue by Deaz750xx** [sheilan102/husky_modified#16]
Hello C2M cannot found the game any advice ?

Thanks

**Comment by FanSeaJay** [comment]
You have to use an older version, such as 1.0.4.3

**Comment by TheBorn** [comment]
> 
> 
> You have to use an older version, such as 1.0.4.3

Can't you update it to detect Black Ops as well?

**Comment by sheilan102** [comment]
C2M 2.0 BETA does not work with BO1, use latest version from this repo.
