### ISSUE TITLE
Safe to run?

### ISSUE THREAD

**Issue by HaveDex** [sheilan102/husky_modified#28]
Do I need to be entirely offline to run this alongside my game? Also why aren't you supporting cracked copies? The moment Steam's gone this tool will be entirely useless. Legitimate copies will inevitably stop working, a cracked copy will never stop working.

**Comment by WindowsXPSux** [comment]
Especially when they still charge $60 for a 10-year-old version of COD

**Comment by sheilan102** [comment]
As mentioned in the readme, no support for pirated copies will be added.
