### ISSUE TITLE
[Question] Radiant Support?

### ISSUE THREAD

**Issue by shit-ware** [sheilan102/husky_modified#3]
As the title states, it is a question (sorry).

For example, if I were to dump the map for mp_paris (Resistance) for IW5, would I be able to open the map inside of Radiant so I can compile it for CoD4?

**Comment by RaGe742004** [comment]
Short answer is no. The .map it exports is for placement of the models. The Geometry is in the OBJ file (which needs to be scaled \ rotated and re-exported into a .map). It's a time consuming process, there is no simple way to export maps with everything in place..you'll still need to do alot of work.

**Comment by shit-ware** [comment]
Ah, alright. Thank you!
