### ISSUE TITLE
Meshes with decals exported with decal material as only material

### ISSUE THREAD

**Issue by 0x8080** [sheilan102/husky_modified#5]
I made this wall decal translucent to show this. This is the only material applied to this mesh.
![image](https://user-images.githubusercontent.com/14355117/82838482-9d995000-9e89-11ea-8135-059bfe6858fe.png)

In game:
![image](https://user-images.githubusercontent.com/14355117/82838587-e9e49000-9e89-11ea-9580-c5951290fc4d.png)

Might run into z conflicts if both the correct material and decal are applied at once

**Comment by sheilan102** [comment]
Decals are not supported
