### ISSUE TITLE
Can't find .ipak or other filetypes for greyhound in Advanced Warfare

### ISSUE THREAD

**Issue by filmedbymatthew** [sheilan102/husky_modified#7]
I am having trouble finding the base.ipak or a similar one by following the tutorial as in the advanced warfare folder there is only .pak files. I searched through my PC but couldn't find a supported filetype to import into greyhound for the image files. This occurs around the 2:00 mark in the COD port maps tutorial

**Comment by sheilan102** [comment]
This isn't Greyhound.
